/**
 * Concept prioritization for academic cards — deterministic, no LLM call.
 *
 * Reads weak-area context from the existing quiz and practice
 * student-learning-context internal routes (Q2: both are read, not just
 * quiz's — practice-derived weak areas are card-eligible from day one).
 * Picking a target and its grounding documentIds is plain code; only the
 * card's rendered text is generated by an LLM (generate.js), and even then
 * never the weak-area label itself ("hide the intervention, not the
 * intelligence").
 *
 * A weak area is only card-eligible once it carries documentIds — that field
 * is added to quiz's and practice's own learning-context output as part of
 * loop closure (see student-learning.js in each service). Until both are
 * wired, this returns no eligible target rather than guessing a chapter.
 */
const DEFAULT_TIMEOUT_MS = 4000;

function trimSlashes(value) {
  return String(value || '').replace(/\/+$/, '');
}

async function fetchLearningContext(baseUrl, path, { studentId, schoolId, token, timeoutMs, fetchImpl }) {
  if (!studentId || !schoolId || !token) return null;
  const params = new URLSearchParams({ studentId, schoolId });
  try {
    const response = await (fetchImpl || fetch)(`${trimSlashes(baseUrl)}${path}?${params}`, {
      method: 'GET',
      headers: { Accept: 'application/json', 'x-internal-service-token': token },
      signal: AbortSignal.timeout(timeoutMs),
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return await response.json();
  } catch (err) {
    console.warn(`[discover] weak-area context unavailable from ${path}:`, err.message);
    return null;
  }
}

/**
 * Fetch and merge weak areas from quiz and practice. Each source area is
 * tagged with `sourceService` so the caller can persist AcademicCard.sourceService,
 * and areas from both services are kept separate (never merged into one row)
 * even when labels collide, because their `missedAttempts` counts are not
 * comparable across services.
 */
async function fetchWeakAreas({
  studentId,
  schoolId,
  quizServiceUrl = process.env.QUIZ_SERVICE_URL || 'http://quiz:3005',
  practiceServiceUrl = process.env.PRACTICE_SERVICE_URL || 'http://practice:3007',
  token = process.env.INTERNAL_SERVICE_TOKEN,
  timeoutMs = DEFAULT_TIMEOUT_MS,
  fetchImpl = fetch,
} = {}) {
  const [quizContext, practiceContext] = await Promise.all([
    fetchLearningContext(quizServiceUrl, '/api/quiz/internal/student-learning-context', {
      studentId, schoolId, token, timeoutMs, fetchImpl,
    }),
    fetchLearningContext(practiceServiceUrl, '/api/practice/internal/student-learning-context', {
      studentId, schoolId, token, timeoutMs, fetchImpl,
    }),
  ]);

  const quizAreas = Array.isArray(quizContext?.weakAreas) ? quizContext.weakAreas : [];
  const practiceAreas = Array.isArray(practiceContext?.weakAreas) ? practiceContext.weakAreas : [];

  return [
    ...quizAreas.map(area => ({ ...area, sourceService: 'quiz' })),
    ...practiceAreas.map(area => ({ ...area, sourceService: 'practice' })),
  ];
}

/**
 * Pick the single best card-eligible weak area.
 *
 * Eligible = carries at least one documentId to ground on. Ranked by
 * missedAttempts desc, then lastSeenAt desc, then label — same order both
 * source services already use internally, so this stays legible.
 */
function selectCardTarget(weakAreas = []) {
  const eligible = weakAreas.filter(area => Array.isArray(area.documentIds) && area.documentIds.length > 0);
  if (!eligible.length) return null;

  const [best] = [...eligible].sort((a, b) => (
    (b.missedAttempts || 0) - (a.missedAttempts || 0)
    || String(b.lastSeenAt || '').localeCompare(String(a.lastSeenAt || ''))
    || String(a.label || '').localeCompare(String(b.label || ''))
  ));

  return {
    label: best.label,
    sourceService: best.sourceService,
    documentIds: best.documentIds,
    conceptTags: Array.isArray(best.conceptTags) ? best.conceptTags : [],
  };
}

module.exports = {
  fetchWeakAreas,
  selectCardTarget,
  DEFAULT_TIMEOUT_MS,
};
